import 'package:flutter/widgets.dart';

enum AppLanguage {
  zhHans('zh-Hans', '简体中文', Locale('zh', 'Hans')),
  zhHant('zh-Hant', '繁體中文', Locale('zh', 'Hant')),
  ja('ja', '日本語', Locale('ja')),
  en('en', 'English', Locale('en')),
  ko('ko', '한국어', Locale('ko'));

  const AppLanguage(this.code, this.nativeName, this.locale);

  final String code;
  final String nativeName;
  final Locale locale;

  static AppLanguage fromCode(String? code) {
    for (final language in values) {
      if (language.code == code) return language;
    }
    return AppLanguage.zhHans;
  }
}

class AppStrings {
  const AppStrings._({
    required this.appTitle,
    required this.workspace,
    required this.dashboard,
    required this.accounts,
    required this.mail,
    required this.settings,
    required this.clawSettings,
    required this.outlookChannel,
    required this.clawChannel,
    required this.outlookChannelDetail,
    required this.clawChannelDetail,
    required this.dashboardSubtitle,
    required this.accountsSubtitle,
    required this.mailSubtitle,
    required this.clawSubtitle,
    required this.settingsSubtitle,
    required this.fetching,
    required this.startFetch,
    required this.clawFetch,
    required this.refreshAccounts,
    required this.syncing,
    required this.fetchLatest,
    required this.syncClaw,
    required this.testConnection,
    required this.languageTitle,
    required this.languageDetail,
    required this.autoStartTitle,
    required this.autoStartDetail,
    required this.enabled,
    required this.autoReceiveTitle,
    required this.autoReceiveDetail,
    required this.portPolicyTitle,
    required this.portPolicyDetail,
    required this.autoSwitch,
    required this.soundTitle,
    required this.soundDetail,
    required this.localApiEngine,
    required this.apiEngineDetail,
    required this.autoReceiveInterval,
    required this.selectSound,
    required this.preview,
    required this.minute,
    required this.bootingApi,
    required this.loadingAccounts,
    required this.ready,
    required this.needsAttention,
    required this.refreshingData,
    required this.refreshFailed,
    required this.fetchingMail,
    required this.noNewMail,
    required this.fetchDone,
    required this.fetchFailed,
    required this.batchFetching,
    required this.batchFetchDone,
    required this.batchFetchFailed,
    required this.fetchingClawMail,
    required this.clawNoNewMail,
    required this.clawFetchDone,
    required this.clawFetchFailed,
    required this.importingAccounts,
    required this.importDone,
    required this.importFailed,
    required this.accountDeleted,
    required this.markerUpdated,
    required this.localApiNotStarted,
    required this.soundMailLabel,
    required this.soundMailDescription,
    required this.soundSoftLabel,
    required this.soundSoftDescription,
    required this.soundNoticeLabel,
    required this.soundNoticeDescription,
    required this.soundSuccessLabel,
    required this.soundSuccessDescription,
    required this.soundUrgentLabel,
    required this.soundUrgentDescription,
  });

  final String appTitle;
  final String workspace;
  final String dashboard;
  final String accounts;
  final String mail;
  final String settings;
  final String clawSettings;
  final String outlookChannel;
  final String clawChannel;
  final String outlookChannelDetail;
  final String clawChannelDetail;
  final String dashboardSubtitle;
  final String accountsSubtitle;
  final String mailSubtitle;
  final String clawSubtitle;
  final String settingsSubtitle;
  final String fetching;
  final String startFetch;
  final String clawFetch;
  final String refreshAccounts;
  final String syncing;
  final String fetchLatest;
  final String syncClaw;
  final String testConnection;
  final String languageTitle;
  final String languageDetail;
  final String autoStartTitle;
  final String autoStartDetail;
  final String enabled;
  final String autoReceiveTitle;
  final String autoReceiveDetail;
  final String portPolicyTitle;
  final String portPolicyDetail;
  final String autoSwitch;
  final String soundTitle;
  final String soundDetail;
  final String localApiEngine;
  final String apiEngineDetail;
  final String autoReceiveInterval;
  final String selectSound;
  final String preview;
  final String minute;
  final String bootingApi;
  final String loadingAccounts;
  final String ready;
  final String needsAttention;
  final String refreshingData;
  final String refreshFailed;
  final String fetchingMail;
  final String noNewMail;
  final String fetchDone;
  final String fetchFailed;
  final String batchFetching;
  final String batchFetchDone;
  final String batchFetchFailed;
  final String fetchingClawMail;
  final String clawNoNewMail;
  final String clawFetchDone;
  final String clawFetchFailed;
  final String importingAccounts;
  final String importDone;
  final String importFailed;
  final String accountDeleted;
  final String markerUpdated;
  final String localApiNotStarted;
  final String soundMailLabel;
  final String soundMailDescription;
  final String soundSoftLabel;
  final String soundSoftDescription;
  final String soundNoticeLabel;
  final String soundNoticeDescription;
  final String soundSuccessLabel;
  final String soundSuccessDescription;
  final String soundUrgentLabel;
  final String soundUrgentDescription;

  String deletedAccounts(int count) => switch (this) {
    final s when identical(s, zhHant) => '已刪除 $count 個帳號',
    final s when identical(s, ja) => '$count 件のアカウントを削除しました',
    final s when identical(s, en) => 'Deleted $count accounts',
    final s when identical(s, ko) => '$count개 계정을 삭제했습니다',
    _ => '已删除 $count 个账号',
  };

  String importResult(int imported, int skipped, int errors) => switch (this) {
    final s when identical(s, zhHant) =>
      '匯入 $imported 個，略過 $skipped 個，錯誤 $errors 個',
    final s when identical(s, ja) =>
      '$imported 件インポート、$skipped 件スキップ、$errors 件エラー',
    final s when identical(s, en) =>
      'Imported $imported, skipped $skipped, errors $errors',
    final s when identical(s, ko) =>
      '$imported개 가져옴, $skipped개 건너뜀, 오류 $errors개',
    _ => '导入 $imported 个，跳过 $skipped 个，错误 $errors 个',
  };

  String selectedAccounts(int count) => switch (this) {
    final s when identical(s, zhHant) => '已選 $count 個',
    final s when identical(s, ja) => '$count 件選択中',
    final s when identical(s, en) => '$count selected',
    final s when identical(s, ko) => '$count개 선택됨',
    _ => '已选 $count',
  };

  String colorName(String source) => switch (source) {
    '蓝' => ui('蓝'),
    '绿' => ui('绿'),
    '橙' => ui('橙'),
    '红' => ui('红'),
    '紫' => ui('紫'),
    '青' => ui('青'),
    _ => source,
  };

  String colorLabel(String source) => switch (this) {
    final s when identical(s, zhHant) => '${colorName(source)}色',
    final s when identical(s, ja) => '${colorName(source)}マーク',
    final s when identical(s, en) => colorName(source),
    final s when identical(s, ko) => colorName(source),
    _ => '${colorName(source)}色',
  };

  String colorMarker(String source) => switch (this) {
    final s when identical(s, zhHant) => '${colorName(source)}色標記',
    final s when identical(s, ja) => '${colorName(source)}マーク',
    final s when identical(s, en) => '${colorName(source)} marker',
    final s when identical(s, ko) => '${colorName(source)} 표시',
    _ => '${colorName(source)}色标记',
  };

  String minutes(int value) => switch (this) {
    final s when identical(s, ja) => '$value 分',
    final s when identical(s, en) => '$value min',
    final s when identical(s, ko) => '$value분',
    _ => '$value $minute',
  };

  String autoReceiveDone(int accounts, int mails) => switch (this) {
    final s when identical(s, zhHant) => '自動接收完成：$accounts 個帳號，$mails 封新郵件',
    final s when identical(s, ja) => '自動受信完了：$accounts 件のアカウント、$mails 件の新着',
    final s when identical(s, en) =>
      'Auto receive complete: $accounts accounts, $mails new mails',
    final s when identical(s, ko) => '자동 수신 완료: 계정 $accounts개, 새 메일 $mails개',
    _ => '自动接收完成：$accounts 个账号，$mails 封新邮件',
  };

  String autoReceivePartial(
    int accounts,
    int failed,
    int mails,
  ) => switch (this) {
    final s when identical(s, zhHant) =>
      '自動接收部分完成：$accounts 個成功，$failed 個失敗，$mails 封新郵件',
    final s when identical(s, ja) =>
      '自動受信一部完了：成功 $accounts、失敗 $failed、新着 $mails',
    final s when identical(s, en) =>
      'Auto receive partial: $accounts ok, $failed failed, $mails new mails',
    final s when identical(s, ko) =>
      '자동 수신 일부 완료: 성공 $accounts개, 실패 $failed개, 새 메일 $mails개',
    _ => '自动接收部分完成：$accounts 个成功，$failed 个失败，$mails 封新邮件',
  };

  String soundLabel(String value) => switch (value) {
    'soft' => soundSoftLabel,
    'notice' => soundNoticeLabel,
    'success' => soundSuccessLabel,
    'urgent' => soundUrgentLabel,
    _ => soundMailLabel,
  };

  String soundDescription(String value) => switch (value) {
    'soft' => soundSoftDescription,
    'notice' => soundNoticeDescription,
    'success' => soundSuccessDescription,
    'urgent' => soundUrgentDescription,
    _ => soundMailDescription,
  };

  String ui(String source) {
    if (identical(this, zhHans)) return source;
    final map = identical(this, zhHant)
        ? _zhHantUi
        : identical(this, ja)
        ? _jaUi
        : identical(this, en)
        ? _enUi
        : _koUi;
    return map[source] ?? source;
  }

  static AppStrings of(AppLanguage language) => switch (language) {
    AppLanguage.zhHant => zhHant,
    AppLanguage.ja => ja,
    AppLanguage.en => en,
    AppLanguage.ko => ko,
    AppLanguage.zhHans => zhHans,
  };

  static const zhHans = AppStrings._(
    appTitle: '邮箱工作台',
    workspace: '邮箱工作台',
    dashboard: '工作台',
    accounts: '账号',
    mail: '邮件',
    settings: '设置',
    clawSettings: 'Claw 设置',
    outlookChannel: 'Outlook 通道',
    clawChannel: 'Claw 通道',
    outlookChannelDetail: '令牌收件与缓存',
    clawChannelDetail: '子邮箱与通讯规则',
    dashboardSubtitle: '收件、状态和最近动态集中处理。',
    accountsSubtitle: '令牌账号、标记和分组管理。',
    mailSubtitle: '缓存阅读、验证码识别和复制。',
    clawSubtitle: 'ClawEmail 绑定与子邮箱同步。',
    settingsSubtitle: '端口、启动、声音和语言偏好。',
    fetching: '收取中',
    startFetch: '开始收取',
    clawFetch: 'Claw 收件',
    refreshAccounts: '刷新账号',
    syncing: '同步中',
    fetchLatest: '收取最新',
    syncClaw: '同步 Claw',
    testConnection: '测试连接',
    languageTitle: '界面语言',
    languageDetail: '切换桌面端主要界面文字。',
    autoStartTitle: '自动启动',
    autoStartDetail: '打开 EXE 后自动创建本地 API 端口。',
    enabled: '已开启',
    autoReceiveTitle: '自动接收',
    autoReceiveDetail: '按间隔后台巡检可用 Outlook 账号，有新邮件时提醒。',
    portPolicyTitle: '端口策略',
    portPolicyDetail: '3000 被占用时改用下一个可用端口。',
    autoSwitch: '自动切换',
    soundTitle: '声音提示',
    soundDetail: '新邮件到达时播放提醒，可选择提示音。',
    localApiEngine: '本地 API 引擎',
    apiEngineDetail: 'Flutter 只负责桌面 UI，收件、数据库和 Claw 适配继续由 Rust sidecar 处理。',
    autoReceiveInterval: '自动接收间隔',
    selectSound: '选择提示音',
    preview: '试听',
    minute: '分钟',
    bootingApi: '正在启动本地 API',
    loadingAccounts: '正在载入账号',
    ready: '就绪',
    needsAttention: '需要处理',
    refreshingData: '正在刷新数据',
    refreshFailed: '刷新失败',
    fetchingMail: '正在收取邮件',
    noNewMail: '无新邮件',
    fetchDone: '收取完成',
    fetchFailed: '收取失败',
    batchFetching: '正在批量收取',
    batchFetchDone: '批量收取完成',
    batchFetchFailed: '批量收取失败',
    fetchingClawMail: '正在收取 Claw 邮件',
    clawNoNewMail: 'Claw 无新邮件',
    clawFetchDone: 'Claw 收取完成',
    clawFetchFailed: 'Claw 收取失败',
    importingAccounts: '正在导入账号',
    importDone: '导入完成',
    importFailed: '导入失败',
    accountDeleted: '账号已删除',
    markerUpdated: '标记已更新',
    localApiNotStarted: '本地 API 未启动。',
    soundMailLabel: '清脆邮件',
    soundMailDescription: '双音阶新邮件提示',
    soundSoftLabel: '轻提示',
    soundSoftDescription: '低打扰柔和提示',
    soundNoticeLabel: '注意提示',
    soundNoticeDescription: '需要处理时使用',
    soundSuccessLabel: '完成提示',
    soundSuccessDescription: '同步完成反馈',
    soundUrgentLabel: '强提醒',
    soundUrgentDescription: '验证码或异常提醒',
  );

  static const zhHant = AppStrings._(
    appTitle: '郵箱工作台',
    workspace: '郵箱工作台',
    dashboard: '工作台',
    accounts: '帳號',
    mail: '郵件',
    settings: '設定',
    clawSettings: 'Claw 設定',
    outlookChannel: 'Outlook 通道',
    clawChannel: 'Claw 通道',
    outlookChannelDetail: 'Token 收件與快取',
    clawChannelDetail: '子郵箱與通訊規則',
    dashboardSubtitle: '集中處理收件、狀態與最近動態。',
    accountsSubtitle: 'Token 帳號、標記與分組管理。',
    mailSubtitle: '快取閱讀、驗證碼辨識與複製。',
    clawSubtitle: 'ClawEmail 綁定與子郵箱同步。',
    settingsSubtitle: '連接埠、啟動、聲音與語言偏好。',
    fetching: '收取中',
    startFetch: '開始收取',
    clawFetch: 'Claw 收件',
    refreshAccounts: '重新整理帳號',
    syncing: '同步中',
    fetchLatest: '收取最新',
    syncClaw: '同步 Claw',
    testConnection: '測試連線',
    languageTitle: '介面語言',
    languageDetail: '切換桌面端主要介面文字。',
    autoStartTitle: '自動啟動',
    autoStartDetail: '開啟 EXE 後自動建立本地 API 連接埠。',
    enabled: '已開啟',
    autoReceiveTitle: '自動接收',
    autoReceiveDetail: '依間隔背景巡檢可用 Outlook 帳號，有新郵件時提醒。',
    portPolicyTitle: '連接埠策略',
    portPolicyDetail: '3000 被占用時改用下一個可用連接埠。',
    autoSwitch: '自動切換',
    soundTitle: '聲音提示',
    soundDetail: '新郵件到達時播放提醒，可選擇提示音。',
    localApiEngine: '本地 API 引擎',
    apiEngineDetail: 'Flutter 只負責桌面 UI，收件、資料庫與 Claw 適配繼續由 Rust sidecar 處理。',
    autoReceiveInterval: '自動接收間隔',
    selectSound: '選擇提示音',
    preview: '試聽',
    minute: '分鐘',
    bootingApi: '正在啟動本地 API',
    loadingAccounts: '正在載入帳號',
    ready: '就緒',
    needsAttention: '需要處理',
    refreshingData: '正在重新整理資料',
    refreshFailed: '重新整理失敗',
    fetchingMail: '正在收取郵件',
    noNewMail: '沒有新郵件',
    fetchDone: '收取完成',
    fetchFailed: '收取失敗',
    batchFetching: '正在批次收取',
    batchFetchDone: '批次收取完成',
    batchFetchFailed: '批次收取失敗',
    fetchingClawMail: '正在收取 Claw 郵件',
    clawNoNewMail: 'Claw 沒有新郵件',
    clawFetchDone: 'Claw 收取完成',
    clawFetchFailed: 'Claw 收取失敗',
    importingAccounts: '正在匯入帳號',
    importDone: '匯入完成',
    importFailed: '匯入失敗',
    accountDeleted: '帳號已刪除',
    markerUpdated: '標記已更新',
    localApiNotStarted: '本地 API 尚未啟動。',
    soundMailLabel: '清脆郵件',
    soundMailDescription: '雙音階新郵件提示',
    soundSoftLabel: '輕提示',
    soundSoftDescription: '低干擾柔和提示',
    soundNoticeLabel: '注意提示',
    soundNoticeDescription: '需要處理時使用',
    soundSuccessLabel: '完成提示',
    soundSuccessDescription: '同步完成回饋',
    soundUrgentLabel: '強提醒',
    soundUrgentDescription: '驗證碼或異常提醒',
  );

  static const ja = AppStrings._(
    appTitle: 'メールワークスペース',
    workspace: 'メールワークスペース',
    dashboard: 'ダッシュボード',
    accounts: 'アカウント',
    mail: 'メール',
    settings: '設定',
    clawSettings: 'Claw 設定',
    outlookChannel: 'Outlook チャネル',
    clawChannel: 'Claw チャネル',
    outlookChannelDetail: 'トークン受信とキャッシュ',
    clawChannelDetail: 'サブメールボックスとルール',
    dashboardSubtitle: '受信、状態、最近の動きをまとめて確認します。',
    accountsSubtitle: 'トークンアカウント、マーク、グループを管理します。',
    mailSubtitle: 'キャッシュ閲覧、認証コード検出、コピーを行います。',
    clawSubtitle: 'ClawEmail の連携とサブメールボックス同期。',
    settingsSubtitle: 'ポート、起動、通知音、言語の設定。',
    fetching: '受信中',
    startFetch: '受信開始',
    clawFetch: 'Claw 受信',
    refreshAccounts: '更新',
    syncing: '同期中',
    fetchLatest: '最新を受信',
    syncClaw: 'Claw 同期',
    testConnection: '接続テスト',
    languageTitle: '表示言語',
    languageDetail: 'デスクトップ UI の主要テキストを切り替えます。',
    autoStartTitle: '自動起動',
    autoStartDetail: 'EXE 起動時にローカル API ポートを作成します。',
    enabled: '有効',
    autoReceiveTitle: '自動受信',
    autoReceiveDetail: '利用可能な Outlook アカウントを定期的に巡回し、新着時に通知します。',
    portPolicyTitle: 'ポート設定',
    portPolicyDetail: '3000 が使用中の場合は次の空きポートを使います。',
    autoSwitch: '自動切替',
    soundTitle: '通知音',
    soundDetail: '新着メール時に通知音を再生します。',
    localApiEngine: 'ローカル API エンジン',
    apiEngineDetail:
        'Flutter はデスクトップ UI を担当し、受信、DB、Claw 連携は Rust sidecar が処理します。',
    autoReceiveInterval: '自動受信間隔',
    selectSound: '通知音を選択',
    preview: '試聴',
    minute: '分',
    bootingApi: 'ローカル API を起動中',
    loadingAccounts: 'アカウントを読み込み中',
    ready: '準備完了',
    needsAttention: '確認が必要',
    refreshingData: 'データを更新中',
    refreshFailed: '更新失敗',
    fetchingMail: 'メールを受信中',
    noNewMail: '新着なし',
    fetchDone: '受信完了',
    fetchFailed: '受信失敗',
    batchFetching: '一括受信中',
    batchFetchDone: '一括受信完了',
    batchFetchFailed: '一括受信失敗',
    fetchingClawMail: 'Claw メールを受信中',
    clawNoNewMail: 'Claw 新着なし',
    clawFetchDone: 'Claw 受信完了',
    clawFetchFailed: 'Claw 受信失敗',
    importingAccounts: 'アカウントをインポート中',
    importDone: 'インポート完了',
    importFailed: 'インポート失敗',
    accountDeleted: 'アカウントを削除しました',
    markerUpdated: 'マークを更新しました',
    localApiNotStarted: 'ローカル API が起動していません。',
    soundMailLabel: 'クリアメール',
    soundMailDescription: '二音階の新着メール通知',
    soundSoftLabel: 'ソフト通知',
    soundSoftDescription: '控えめな柔らかい通知',
    soundNoticeLabel: '注意通知',
    soundNoticeDescription: '確認が必要な時に使用',
    soundSuccessLabel: '完了通知',
    soundSuccessDescription: '同期完了のフィードバック',
    soundUrgentLabel: '強い通知',
    soundUrgentDescription: '認証コードや異常時の通知',
  );

  static const en = AppStrings._(
    appTitle: 'Mail Workspace',
    workspace: 'Mail Workspace',
    dashboard: 'Dashboard',
    accounts: 'Accounts',
    mail: 'Mail',
    settings: 'Settings',
    clawSettings: 'Claw Settings',
    outlookChannel: 'Outlook Channel',
    clawChannel: 'Claw Channel',
    outlookChannelDetail: 'Token fetch and cache',
    clawChannelDetail: 'Mailboxes and rules',
    dashboardSubtitle: 'Mail, status, and recent activity in one place.',
    accountsSubtitle: 'Token accounts, markers, and grouping.',
    mailSubtitle: 'Cached reading, code detection, and copy helpers.',
    clawSubtitle: 'ClawEmail binding and mailbox sync.',
    settingsSubtitle: 'Ports, startup, sound, and language preferences.',
    fetching: 'Fetching',
    startFetch: 'Start Fetch',
    clawFetch: 'Claw Fetch',
    refreshAccounts: 'Refresh Accounts',
    syncing: 'Syncing',
    fetchLatest: 'Fetch Latest',
    syncClaw: 'Sync Claw',
    testConnection: 'Test Connection',
    languageTitle: 'Interface Language',
    languageDetail: 'Switch the main desktop interface text.',
    autoStartTitle: 'Auto Start',
    autoStartDetail: 'Create the local API port when the EXE opens.',
    enabled: 'Enabled',
    autoReceiveTitle: 'Auto Receive',
    autoReceiveDetail:
        'Check available Outlook accounts in the background and alert on new mail.',
    portPolicyTitle: 'Port Policy',
    portPolicyDetail: 'Use the next free port when 3000 is occupied.',
    autoSwitch: 'Auto Switch',
    soundTitle: 'Sound Alert',
    soundDetail: 'Play a selectable sound when new mail arrives.',
    localApiEngine: 'Local API Engine',
    apiEngineDetail:
        'Flutter handles the desktop UI; mail, database, and Claw integration are handled by the Rust sidecar.',
    autoReceiveInterval: 'Auto receive interval',
    selectSound: 'Select sound',
    preview: 'Preview',
    minute: 'min',
    bootingApi: 'Starting local API',
    loadingAccounts: 'Loading accounts',
    ready: 'Ready',
    needsAttention: 'Needs attention',
    refreshingData: 'Refreshing data',
    refreshFailed: 'Refresh failed',
    fetchingMail: 'Fetching mail',
    noNewMail: 'No new mail',
    fetchDone: 'Fetch complete',
    fetchFailed: 'Fetch failed',
    batchFetching: 'Batch fetching',
    batchFetchDone: 'Batch fetch complete',
    batchFetchFailed: 'Batch fetch failed',
    fetchingClawMail: 'Fetching Claw mail',
    clawNoNewMail: 'No new Claw mail',
    clawFetchDone: 'Claw fetch complete',
    clawFetchFailed: 'Claw fetch failed',
    importingAccounts: 'Importing accounts',
    importDone: 'Import complete',
    importFailed: 'Import failed',
    accountDeleted: 'Account deleted',
    markerUpdated: 'Marker updated',
    localApiNotStarted: 'Local API is not running.',
    soundMailLabel: 'Crisp Mail',
    soundMailDescription: 'Two-tone new mail alert',
    soundSoftLabel: 'Soft Alert',
    soundSoftDescription: 'Low-interruption gentle alert',
    soundNoticeLabel: 'Notice Alert',
    soundNoticeDescription: 'Use when attention is needed',
    soundSuccessLabel: 'Success Alert',
    soundSuccessDescription: 'Feedback after sync completes',
    soundUrgentLabel: 'Urgent Alert',
    soundUrgentDescription: 'For codes or errors',
  );

  static const ko = AppStrings._(
    appTitle: '메일 작업대',
    workspace: '메일 작업대',
    dashboard: '대시보드',
    accounts: '계정',
    mail: '메일',
    settings: '설정',
    clawSettings: 'Claw 설정',
    outlookChannel: 'Outlook 채널',
    clawChannel: 'Claw 채널',
    outlookChannelDetail: '토큰 수신 및 캐시',
    clawChannelDetail: '하위 메일함과 규칙',
    dashboardSubtitle: '수신, 상태, 최근 활동을 한곳에서 확인합니다.',
    accountsSubtitle: '토큰 계정, 표시, 그룹을 관리합니다.',
    mailSubtitle: '캐시 읽기, 인증 코드 감지, 복사 도구.',
    clawSubtitle: 'ClawEmail 연결 및 하위 메일함 동기화.',
    settingsSubtitle: '포트, 시작, 소리, 언어 설정.',
    fetching: '수신 중',
    startFetch: '수신 시작',
    clawFetch: 'Claw 수신',
    refreshAccounts: '계정 새로고침',
    syncing: '동기화 중',
    fetchLatest: '최신 수신',
    syncClaw: 'Claw 동기화',
    testConnection: '연결 테스트',
    languageTitle: '인터페이스 언어',
    languageDetail: '데스크톱 주요 UI 문구를 전환합니다.',
    autoStartTitle: '자동 시작',
    autoStartDetail: 'EXE 실행 시 로컬 API 포트를 만듭니다.',
    enabled: '켜짐',
    autoReceiveTitle: '자동 수신',
    autoReceiveDetail: '사용 가능한 Outlook 계정을 백그라운드로 확인하고 새 메일을 알립니다.',
    portPolicyTitle: '포트 정책',
    portPolicyDetail: '3000이 사용 중이면 다음 사용 가능 포트를 씁니다.',
    autoSwitch: '자동 전환',
    soundTitle: '소리 알림',
    soundDetail: '새 메일 도착 시 선택한 알림음을 재생합니다.',
    localApiEngine: '로컬 API 엔진',
    apiEngineDetail:
        'Flutter는 데스크톱 UI를 맡고, 수신, DB, Claw 연동은 Rust sidecar가 처리합니다.',
    autoReceiveInterval: '자동 수신 간격',
    selectSound: '알림음 선택',
    preview: '미리 듣기',
    minute: '분',
    bootingApi: '로컬 API 시작 중',
    loadingAccounts: '계정 불러오는 중',
    ready: '준비됨',
    needsAttention: '확인 필요',
    refreshingData: '데이터 새로고침 중',
    refreshFailed: '새로고침 실패',
    fetchingMail: '메일 수신 중',
    noNewMail: '새 메일 없음',
    fetchDone: '수신 완료',
    fetchFailed: '수신 실패',
    batchFetching: '일괄 수신 중',
    batchFetchDone: '일괄 수신 완료',
    batchFetchFailed: '일괄 수신 실패',
    fetchingClawMail: 'Claw 메일 수신 중',
    clawNoNewMail: 'Claw 새 메일 없음',
    clawFetchDone: 'Claw 수신 완료',
    clawFetchFailed: 'Claw 수신 실패',
    importingAccounts: '계정 가져오는 중',
    importDone: '가져오기 완료',
    importFailed: '가져오기 실패',
    accountDeleted: '계정 삭제됨',
    markerUpdated: '표시가 업데이트됨',
    localApiNotStarted: '로컬 API가 시작되지 않았습니다.',
    soundMailLabel: '맑은 메일음',
    soundMailDescription: '두 음의 새 메일 알림',
    soundSoftLabel: '부드러운 알림',
    soundSoftDescription: '방해가 적은 부드러운 알림',
    soundNoticeLabel: '주의 알림',
    soundNoticeDescription: '확인이 필요할 때 사용',
    soundSuccessLabel: '완료 알림',
    soundSuccessDescription: '동기화 완료 피드백',
    soundUrgentLabel: '강한 알림',
    soundUrgentDescription: '인증 코드 또는 오류 알림',
  );

  static const _zhHantUi = {
    'Claw 子邮箱': 'Claw 子郵箱',
    '已导入账号': '已匯入帳號',
    '已同步列表': '已同步清單',
    '全部令牌已载入': '所有 Token 已載入',
    '可用子邮箱': '可用子郵箱',
    '可立即收件': '可立即收件',
    '通讯规则正常': '通訊規則正常',
    '等待同步': '等待同步',
    '缓存邮件': '快取郵件',
    '收件箱': '收件匣',
    '本地可读': '本地可讀',
    '待处理异常': '待處理異常',
    '优先修复': '優先修復',
    '今日收件队列': '今日收件佇列',
    '管理账号': '管理帳號',
    '未命名子邮箱': '未命名子郵箱',
    'Outlook 令牌账号': 'Outlook Token 帳號',
    '可用': '可用',
    '收件同步': '收件同步',
    '待执行': '待執行',
    '账号将同步到本地缓存，完成后可在邮件页直接阅读。': '帳號將同步到本地快取，完成後可在郵件頁直接閱讀。',
    '最近邮件': '最近郵件',
    '暂无邮件': '暫無郵件',
    '暂无 Claw 子邮箱，先到 Claw 设置绑定并同步。': '暫無 Claw 子郵箱，請先到 Claw 設定綁定並同步。',
    '暂无账号，先导入 Outlook 令牌账号。': '暫無帳號，請先匯入 Outlook Token 帳號。',
    '有异常': '有異常',
    '缓存': '快取',
    '搜索邮件、验证码或发件人': '搜尋郵件、驗證碼或寄件者',
    '先在 Claw 账号页选择子邮箱。': '請先在 Claw 帳號頁選擇子郵箱。',
    '先在账号页选择邮箱。': '請先在帳號頁選擇郵箱。',
    '收取': '收取',
    '选择一封邮件开始阅读': '選擇一封郵件開始閱讀',
    '无正文预览。': '無正文預覽。',
    '暂无缓存邮件': '暫無快取郵件',
    '先选择一个 Claw 子邮箱': '請先選擇一個 Claw 子郵箱',
    '先选择一个账号': '請先選擇一個帳號',
    '点击收取后会从 Claw Coremail 拉取并写入本地缓存。': '點擊收取後會從 Claw Coremail 拉取並寫入本地快取。',
    '点击收取后会显示 Graph / IMAP / 缓存来源。': '點擊收取後會顯示 Graph / IMAP / 快取來源。',
    '到 Claw 账号页选择子邮箱后再读取邮件。': '到 Claw 帳號頁選擇子郵箱後再讀取郵件。',
    '到账号页选择邮箱后再读取邮件。': '到帳號頁選擇郵箱後再讀取郵件。',
    '立即收取': '立即收取',
    '邮箱地址已复制': '郵箱地址已複製',
    '异常': '異常',
    '复制邮箱': '複製郵箱',
    '删除': '刪除',
    '已刷新': '已重新整理',
    '批量操作': '批次操作',
    '批量收件': '批次收件',
    '选择账号': '選擇帳號',
    '点击左侧账号后，可查看状态、标记颜色并执行收件。': '點擊左側帳號後，可查看狀態、標記顏色並執行收件。',
    '最近刷新': '最近重新整理',
    '数据库维护': '資料庫維護',
    '处理中': '處理中',
    '文件': '檔案',
    '大小': '大小',
    '重复/孤立': '重複/孤立',
    '健康检查': '健康檢查',
    '预检查': '預檢查',
    '修复缓存': '修復快取',
    '压缩优化': '壓縮最佳化',
    '邮件助手': '郵件助手',
    '待选择': '待選擇',
    '已识别': '已辨識',
    '未识别': '未辨識',
    '验证码': '驗證碼',
    '等待识别': '等待辨識',
    '自动提取当前邮件正文中的 4-8 位数字。': '自動提取目前郵件正文中的 4-8 位數字。',
    '日期': '日期',
    '正文': '正文',
    '无预览': '無預覽',
    '已缓存': '已快取',
    '当前邮件': '目前郵件',
    '选择一封邮件后显示发件人、日期和缓存状态。': '選擇一封郵件後顯示寄件者、日期和快取狀態。',
    '快捷动作': '快捷動作',
    '复制验证码': '複製驗證碼',
    '未识别到数字验证码': '未辨識到數字驗證碼',
    '复制正文': '複製正文',
    '当前邮件没有正文缓存': '目前郵件沒有正文快取',
    '复制当前邮件纯文本': '複製目前郵件純文字',
    '已复制到剪贴板': '已複製到剪貼簿',
    '刷新': '重新整理',
    '浏览器授权': '瀏覽器授權',
    '批量导入': '批次匯入',
    '账号信息': '帳號資訊',
    '标记': '標記',
    '状态': '狀態',
    '操作': '操作',
    '同步': '同步',
    '当前显示 ClawEmail 子邮箱，不混用 Outlook 令牌账号。':
        '目前顯示 ClawEmail 子郵箱，不混用 Outlook Token 帳號。',
    '暂无 Claw 子邮箱': '暫無 Claw 子郵箱',
    '子邮箱': '子郵箱',
    '类型': '類型',
    '复制子邮箱': '複製子郵箱',
    'Claw 子邮箱已复制': 'Claw 子郵箱已複製',
    '选择子邮箱': '選擇子郵箱',
    '点击左侧 Claw 子邮箱后查看状态。': '點擊左側 Claw 子郵箱後查看狀態。',
    '来源': '來源',
    '查看邮件': '查看郵件',
    '批量导入账号': '批次匯入帳號',
    '每行格式：邮箱----密码----client_id----refresh_token。如果 client_id 和令牌顺序反了，后端会自动修正。':
        '每行格式：郵箱----密碼----client_id----refresh_token。如果 client_id 和 Token 順序反了，後端會自動修正。',
    '取消': '取消',
    '导入中': '匯入中',
    '导入': '匯入',
    '浏览器授权登录': '瀏覽器授權登入',
    '会打开系统浏览器完成 Microsoft 授权，成功后自动写入账号。': '會開啟系統瀏覽器完成 Microsoft 授權，成功後自動寫入帳號。',
    '适合没有现成 refresh token 的普通 Outlook / Hotmail 账号。':
        '適合沒有現成 refresh token 的普通 Outlook / Hotmail 帳號。',
    '等待授权': '等待授權',
    '打开浏览器': '開啟瀏覽器',
    '正在创建授权会话...': '正在建立授權工作階段...',
    '授权会话返回不完整。': '授權工作階段回傳不完整。',
    '浏览器已打开，请完成登录授权。': '瀏覽器已開啟，請完成登入授權。',
    '账号': '帳號',
    '已授权并导入': '已授權並匯入',
    '授权失败': '授權失敗',
    '授权等待超时，请重新打开浏览器授权。': '授權等待逾時，請重新開啟瀏覽器授權。',
    '已绑定': '已綁定',
    '未绑定': '未綁定',
    '绑定 Claw 后可同步子邮箱和通讯规则。': '綁定 Claw 後可同步子郵箱和通訊規則。',
    'Claw 登录邮箱': 'Claw 登入郵箱',
    '发送验证码': '傳送驗證碼',
    '验证码已发送': '驗證碼已傳送',
    '绑定并同步': '綁定並同步',
    'Claw 已绑定并同步': 'Claw 已綁定並同步',
    '刷新授权': '重新整理授權',
    'Claw 授权已刷新': 'Claw 授權已重新整理',
    '子邮箱已创建': '子郵箱已建立',
    '子邮箱已同步': '子郵箱已同步',
    '新子邮箱后缀': '新子郵箱後綴',
    '创建': '建立',
    '账号标记': '帳號標記',
    '未标记': '未標記',
    '标记颜色': '標記顏色',
    '清除标记': '清除標記',
    '清除': '清除',
    '蓝': '藍',
    '绿': '綠',
    '橙': '橙',
    '红': '紅',
    '紫': '紫',
    '青': '青',
    '搜索邮箱、名称或 client id': '搜尋郵箱、名稱或 client id',
    '健康检查完成': '健康檢查完成',
    '修复完成，剩余问题': '修復完成，剩餘問題',
    '已压缩': '已壓縮',
    '预检查完成': '預檢查完成',
    '可处理：空 ID': '可處理：空 ID',
    '，重复': '，重複',
    '，孤立': '，孤立',
  };

  static const _jaUi = {
    'Claw 子邮箱': 'Claw サブメール',
    '已导入账号': '登録済みアカウント',
    '已同步列表': '同期済みリスト',
    '全部令牌已载入': '全トークン読み込み済み',
    '可用子邮箱': '利用可能なサブメール',
    '可立即收件': '受信可能',
    '通讯规则正常': 'ルール正常',
    '等待同步': '同期待ち',
    '缓存邮件': 'キャッシュメール',
    '收件箱': '受信トレイ',
    '本地可读': 'ローカル閲覧可',
    '待处理异常': '未対応の異常',
    '优先修复': '優先修正',
    '今日收件队列': '本日の受信キュー',
    '管理账号': 'アカウント管理',
    '未命名子邮箱': '未命名サブメール',
    'Outlook 令牌账号': 'Outlook トークンアカウント',
    '可用': '利用可',
    '收件同步': '受信同期',
    '待执行': '待機中',
    '账号将同步到本地缓存，完成后可在邮件页直接阅读。': 'アカウントをローカルキャッシュへ同期し、完了後はメール画面で直接読めます。',
    '最近邮件': '最近のメール',
    '暂无邮件': 'メールはまだありません',
    '暂无 Claw 子邮箱，先到 Claw 设置绑定并同步。': 'Claw サブメールがありません。先に Claw 設定で連携して同期してください。',
    '暂无账号，先导入 Outlook 令牌账号。': 'アカウントがありません。先に Outlook トークンアカウントをインポートしてください。',
    '有异常': '異常あり',
    '缓存': 'キャッシュ',
    '搜索邮件、验证码或发件人': 'メール、認証コード、送信者を検索',
    '先在 Claw 账号页选择子邮箱。': '先に Claw アカウント画面でサブメールを選択してください。',
    '先在账号页选择邮箱。': '先にアカウント画面でメールを選択してください。',
    '收取': '受信',
    '选择一封邮件开始阅读': 'メールを選択して読み始めます',
    '无正文预览。': '本文プレビューはありません。',
    '暂无缓存邮件': 'キャッシュメールはまだありません',
    '先选择一个 Claw 子邮箱': 'Claw サブメールを選択してください',
    '先选择一个账号': 'アカウントを選択してください',
    '点击收取后会从 Claw Coremail 拉取并写入本地缓存。':
        '受信を押すと Claw Coremail から取得してローカルキャッシュに保存します。',
    '点击收取后会显示 Graph / IMAP / 缓存来源。': '受信後に Graph / IMAP / キャッシュの取得元を表示します。',
    '到 Claw 账号页选择子邮箱后再读取邮件。': 'Claw アカウント画面でサブメールを選択してから読み込んでください。',
    '到账号页选择邮箱后再读取邮件。': 'アカウント画面でメールを選択してから読み込んでください。',
    '立即收取': '今すぐ受信',
    '邮箱地址已复制': 'メールアドレスをコピーしました',
    '异常': '異常',
    '复制邮箱': 'メールをコピー',
    '删除': '削除',
    '已刷新': '更新済み',
    '批量操作': '一括操作',
    '批量收件': '一括受信',
    '选择账号': 'アカウントを選択',
    '点击左侧账号后，可查看状态、标记颜色并执行收件。': '左のアカウントを選択すると、状態やマーク色を確認し受信できます。',
    '最近刷新': '最終更新',
    '数据库维护': 'データベース保守',
    '处理中': '処理中',
    '文件': 'ファイル',
    '大小': 'サイズ',
    '重复/孤立': '重複/孤立',
    '健康检查': 'ヘルスチェック',
    '预检查': '事前チェック',
    '修复缓存': 'キャッシュ修復',
    '压缩优化': '圧縮最適化',
    '邮件助手': 'メールアシスト',
    '待选择': '未選択',
    '已识别': '検出済み',
    '未识别': '未検出',
    '验证码': '認証コード',
    '等待识别': '検出待ち',
    '自动提取当前邮件正文中的 4-8 位数字。': '現在のメール本文から 4-8 桁の数字を自動抽出します。',
    '日期': '日付',
    '正文': '本文',
    '无预览': 'プレビューなし',
    '已缓存': 'キャッシュ済み',
    '当前邮件': '現在のメール',
    '选择一封邮件后显示发件人、日期和缓存状态。': 'メールを選択すると送信者、日付、キャッシュ状態を表示します。',
    '快捷动作': 'クイック操作',
    '复制验证码': '認証コードをコピー',
    '未识别到数字验证码': '数字コードは検出されていません',
    '复制正文': '本文をコピー',
    '当前邮件没有正文缓存': '現在のメールに本文キャッシュがありません',
    '复制当前邮件纯文本': '現在のメール本文をコピー',
    '已复制到剪贴板': 'クリップボードにコピーしました',
    '刷新': '更新',
    '浏览器授权': 'ブラウザ認証',
    '批量导入': '一括インポート',
    '账号信息': 'アカウント情報',
    '标记': 'マーク',
    '状态': '状態',
    '操作': '操作',
    '同步': '同期',
    '当前显示 ClawEmail 子邮箱，不混用 Outlook 令牌账号。':
        '現在は ClawEmail サブメールを表示しており、Outlook トークンアカウントとは混在しません。',
    '暂无 Claw 子邮箱': 'Claw サブメールはまだありません',
    '子邮箱': 'サブメール',
    '类型': '種類',
    '复制子邮箱': 'サブメールをコピー',
    'Claw 子邮箱已复制': 'Claw サブメールをコピーしました',
    '选择子邮箱': 'サブメールを選択',
    '点击左侧 Claw 子邮箱后查看状态。': '左の Claw サブメールを選択すると状態を確認できます。',
    '来源': 'ソース',
    '查看邮件': 'メールを見る',
    '批量导入账号': 'アカウント一括インポート',
    '每行格式：邮箱----密码----client_id----refresh_token。如果 client_id 和令牌顺序反了，后端会自动修正。':
        '1 行の形式: メール----パスワード----client_id----refresh_token。client_id とトークンの順序が逆でもバックエンドが自動修正します。',
    '取消': 'キャンセル',
    '导入中': 'インポート中',
    '导入': 'インポート',
    '浏览器授权登录': 'ブラウザ認証ログイン',
    '会打开系统浏览器完成 Microsoft 授权，成功后自动写入账号。':
        'システムブラウザで Microsoft 認証を完了し、成功後にアカウントへ自動保存します。',
    '适合没有现成 refresh token 的普通 Outlook / Hotmail 账号。':
        '既存の refresh token がない通常の Outlook / Hotmail アカウント向けです。',
    '等待授权': '認証待ち',
    '打开浏览器': 'ブラウザを開く',
    '正在创建授权会话...': '認証セッションを作成中...',
    '授权会话返回不完整。': '認証セッションの応答が不完全です。',
    '浏览器已打开，请完成登录授权。': 'ブラウザを開きました。ログイン認証を完了してください。',
    '账号': 'アカウント',
    '已授权并导入': '認証してインポートしました',
    '授权失败': '認証に失敗しました',
    '授权等待超时，请重新打开浏览器授权。': '認証待ちがタイムアウトしました。ブラウザ認証をやり直してください。',
    '已绑定': '連携済み',
    '未绑定': '未連携',
    '绑定 Claw 后可同步子邮箱和通讯规则。': 'Claw 連携後にサブメールとルールを同期できます。',
    'Claw 登录邮箱': 'Claw ログインメール',
    '发送验证码': '認証コード送信',
    '验证码已发送': '認証コードを送信しました',
    '绑定并同步': '連携して同期',
    'Claw 已绑定并同步': 'Claw を連携して同期しました',
    '刷新授权': '認証を更新',
    'Claw 授权已刷新': 'Claw 認証を更新しました',
    '子邮箱已创建': 'サブメールを作成しました',
    '子邮箱已同步': 'サブメールを同期しました',
    '新子邮箱后缀': '新しいサブメールの接尾辞',
    '创建': '作成',
    '账号标记': 'アカウントマーク',
    '未标记': '未設定',
    '标记颜色': 'マーク色',
    '清除标记': 'マークをクリア',
    '清除': 'クリア',
    '蓝': '青',
    '绿': '緑',
    '橙': 'オレンジ',
    '红': '赤',
    '紫': '紫',
    '青': 'シアン',
    '搜索邮箱、名称或 client id': 'メール、名前、client id を検索',
    '健康检查完成': 'ヘルスチェック完了',
    '修复完成，剩余问题': '修復完了、残りの問題',
    '已压缩': '圧縮しました',
    '预检查完成': '事前チェック完了',
    '可处理：空 ID': '処理可能: 空 ID',
    '，重复': '、重複',
    '，孤立': '、孤立',
  };

  static const _enUi = {
    'Claw 子邮箱': 'Claw Mailboxes',
    '已导入账号': 'Imported Accounts',
    '已同步列表': 'Synced list',
    '全部令牌已载入': 'All tokens loaded',
    '可用子邮箱': 'Available Mailboxes',
    '可立即收件': 'Ready to Fetch',
    '通讯规则正常': 'Rules healthy',
    '等待同步': 'Waiting to sync',
    '缓存邮件': 'Cached Mail',
    '收件箱': 'Inbox',
    '本地可读': 'Readable locally',
    '待处理异常': 'Open Issues',
    '优先修复': 'Fix first',
    '今日收件队列': "Today's Queue",
    '管理账号': 'Manage Accounts',
    '未命名子邮箱': 'Unnamed mailbox',
    'Outlook 令牌账号': 'Outlook token account',
    '可用': 'Available',
    '收件同步': 'Mail Sync',
    '待执行': 'Pending',
    '账号将同步到本地缓存，完成后可在邮件页直接阅读。':
        'Accounts sync into the local cache, then can be read directly in Mail.',
    '最近邮件': 'Recent Mail',
    '暂无邮件': 'No mail yet',
    '暂无 Claw 子邮箱，先到 Claw 设置绑定并同步。':
        'No Claw mailboxes yet. Bind and sync in Claw Settings first.',
    '暂无账号，先导入 Outlook 令牌账号。':
        'No accounts yet. Import Outlook token accounts first.',
    '有异常': 'Issue',
    '缓存': 'Cache',
    '搜索邮件、验证码或发件人': 'Search mail, codes, or senders',
    '先在 Claw 账号页选择子邮箱。': 'Select a Claw mailbox on the Accounts page first.',
    '先在账号页选择邮箱。': 'Select an account on the Accounts page first.',
    '收取': 'Fetch',
    '选择一封邮件开始阅读': 'Select a message to start reading',
    '无正文预览。': 'No body preview.',
    '暂无缓存邮件': 'No cached mail yet',
    '先选择一个 Claw 子邮箱': 'Select a Claw mailbox first',
    '先选择一个账号': 'Select an account first',
    '点击收取后会从 Claw Coremail 拉取并写入本地缓存。':
        'Fetch pulls from Claw Coremail and writes to the local cache.',
    '点击收取后会显示 Graph / IMAP / 缓存来源。':
        'Fetch will show the Graph / IMAP / cache source.',
    '到 Claw 账号页选择子邮箱后再读取邮件。':
        'Choose a Claw mailbox on Accounts before reading mail.',
    '到账号页选择邮箱后再读取邮件。': 'Choose an account before reading mail.',
    '立即收取': 'Fetch Now',
    '邮箱地址已复制': 'Email address copied',
    '异常': 'Error',
    '复制邮箱': 'Copy Email',
    '删除': 'Delete',
    '已刷新': 'Refreshed',
    '批量操作': 'Batch Actions',
    '批量收件': 'Batch Fetch',
    '选择账号': 'Select Account',
    '点击左侧账号后，可查看状态、标记颜色并执行收件。':
        'Select an account on the left to view status, marker color, and fetch mail.',
    '最近刷新': 'Last Refresh',
    '数据库维护': 'Database Maintenance',
    '处理中': 'Working',
    '文件': 'File',
    '大小': 'Size',
    '重复/孤立': 'Duplicate / Orphan',
    '健康检查': 'Health Check',
    '预检查': 'Precheck',
    '修复缓存': 'Repair Cache',
    '压缩优化': 'Compact',
    '邮件助手': 'Mail Helper',
    '待选择': 'Waiting',
    '已识别': 'Detected',
    '未识别': 'Not Detected',
    '验证码': 'Code',
    '等待识别': 'Waiting',
    '自动提取当前邮件正文中的 4-8 位数字。':
        'Automatically extracts 4-8 digit codes from the current mail body.',
    '日期': 'Date',
    '正文': 'Body',
    '无预览': 'No preview',
    '已缓存': 'Cached',
    '当前邮件': 'Current Mail',
    '选择一封邮件后显示发件人、日期和缓存状态。':
        'Select a message to show sender, date, and cache status.',
    '快捷动作': 'Quick Actions',
    '复制验证码': 'Copy Code',
    '未识别到数字验证码': 'No numeric code detected',
    '复制正文': 'Copy Body',
    '当前邮件没有正文缓存': 'No cached body for this message',
    '复制当前邮件纯文本': 'Copy current plain text',
    '已复制到剪贴板': 'Copied to clipboard',
    '刷新': 'Refresh',
    '浏览器授权': 'Browser Login',
    '批量导入': 'Batch Import',
    '账号信息': 'Account',
    '标记': 'Marker',
    '状态': 'Status',
    '操作': 'Actions',
    '同步': 'Sync',
    '当前显示 ClawEmail 子邮箱，不混用 Outlook 令牌账号。':
        'Showing ClawEmail mailboxes only, separate from Outlook token accounts.',
    '暂无 Claw 子邮箱': 'No Claw mailboxes yet',
    '子邮箱': 'Mailbox',
    '类型': 'Type',
    '复制子邮箱': 'Copy Mailbox',
    'Claw 子邮箱已复制': 'Claw mailbox copied',
    '选择子邮箱': 'Select Mailbox',
    '点击左侧 Claw 子邮箱后查看状态。':
        'Select a Claw mailbox on the left to view its status.',
    '来源': 'Source',
    '查看邮件': 'View Mail',
    '批量导入账号': 'Batch Import Accounts',
    '每行格式：邮箱----密码----client_id----refresh_token。如果 client_id 和令牌顺序反了，后端会自动修正。':
        'One line per account: email----password----client_id----refresh_token. If client_id and token are reversed, the backend corrects them.',
    '取消': 'Cancel',
    '导入中': 'Importing',
    '导入': 'Import',
    '浏览器授权登录': 'Browser Authorization Login',
    '会打开系统浏览器完成 Microsoft 授权，成功后自动写入账号。':
        'Opens the system browser for Microsoft authorization and saves the account after success.',
    '适合没有现成 refresh token 的普通 Outlook / Hotmail 账号。':
        'For regular Outlook / Hotmail accounts without an existing refresh token.',
    '等待授权': 'Waiting',
    '打开浏览器': 'Open Browser',
    '正在创建授权会话...': 'Creating authorization session...',
    '授权会话返回不完整。': 'Authorization session response is incomplete.',
    '浏览器已打开，请完成登录授权。': 'Browser opened. Complete the login authorization.',
    '账号': 'Account',
    '已授权并导入': 'authorized and imported',
    '授权失败': 'Authorization failed',
    '授权等待超时，请重新打开浏览器授权。': 'Authorization timed out. Open the browser again.',
    '已绑定': 'Connected',
    '未绑定': 'Not Connected',
    '绑定 Claw 后可同步子邮箱和通讯规则。':
        'Connect Claw to sync mailboxes and communication rules.',
    'Claw 登录邮箱': 'Claw Login Email',
    '发送验证码': 'Send Code',
    '验证码已发送': 'Code sent',
    '绑定并同步': 'Connect and Sync',
    'Claw 已绑定并同步': 'Claw connected and synced',
    '刷新授权': 'Refresh Auth',
    'Claw 授权已刷新': 'Claw auth refreshed',
    '子邮箱已创建': 'Mailbox created',
    '子邮箱已同步': 'Mailboxes synced',
    '新子邮箱后缀': 'New mailbox suffix',
    '创建': 'Create',
    '账号标记': 'Account Marker',
    '未标记': 'Unmarked',
    '标记颜色': 'Marker Color',
    '清除标记': 'Clear Marker',
    '清除': 'Clear',
    '蓝': 'Blue',
    '绿': 'Green',
    '橙': 'Orange',
    '红': 'Red',
    '紫': 'Purple',
    '青': 'Cyan',
    '搜索邮箱、名称或 client id': 'Search email, name, or client id',
    '健康检查完成': 'Health check complete',
    '修复完成，剩余问题': 'Repair complete, remaining issues',
    '已压缩': 'Compacted',
    '预检查完成': 'Precheck complete',
    '可处理：空 ID': 'Can fix: empty ID',
    '，重复': ', duplicate',
    '，孤立': ', orphan',
  };

  static const _koUi = {
    'Claw 子邮箱': 'Claw 하위 메일함',
    '已导入账号': '가져온 계정',
    '已同步列表': '동기화된 목록',
    '全部令牌已载入': '모든 토큰 로드됨',
    '可用子邮箱': '사용 가능한 메일함',
    '可立即收件': '즉시 수신 가능',
    '通讯规则正常': '규칙 정상',
    '等待同步': '동기화 대기',
    '缓存邮件': '캐시 메일',
    '收件箱': '받은 편지함',
    '本地可读': '로컬에서 읽기 가능',
    '待处理异常': '처리할 문제',
    '优先修复': '우선 수정',
    '今日收件队列': '오늘의 수신 대기열',
    '管理账号': '계정 관리',
    '未命名子邮箱': '이름 없는 하위 메일함',
    'Outlook 令牌账号': 'Outlook 토큰 계정',
    '可用': '사용 가능',
    '收件同步': '메일 동기화',
    '待执行': '대기 중',
    '账号将同步到本地缓存，完成后可在邮件页直接阅读。': '계정은 로컬 캐시에 동기화되며 완료 후 메일 화면에서 바로 읽을 수 있습니다.',
    '最近邮件': '최근 메일',
    '暂无邮件': '메일 없음',
    '暂无 Claw 子邮箱，先到 Claw 设置绑定并同步。':
        'Claw 하위 메일함이 없습니다. 먼저 Claw 설정에서 연결하고 동기화하세요.',
    '暂无账号，先导入 Outlook 令牌账号。': '계정이 없습니다. 먼저 Outlook 토큰 계정을 가져오세요.',
    '有异常': '문제 있음',
    '缓存': '캐시',
    '搜索邮件、验证码或发件人': '메일, 인증 코드 또는 보낸 사람 검색',
    '先在 Claw 账号页选择子邮箱。': '먼저 Claw 계정 페이지에서 하위 메일함을 선택하세요.',
    '先在账号页选择邮箱。': '먼저 계정 페이지에서 메일을 선택하세요.',
    '收取': '수신',
    '选择一封邮件开始阅读': '메일을 선택해 읽기 시작하세요',
    '无正文预览。': '본문 미리보기가 없습니다.',
    '暂无缓存邮件': '캐시된 메일 없음',
    '先选择一个 Claw 子邮箱': 'Claw 하위 메일함을 먼저 선택하세요',
    '先选择一个账号': '계정을 먼저 선택하세요',
    '点击收取后会从 Claw Coremail 拉取并写入本地缓存。':
        '수신을 누르면 Claw Coremail에서 가져와 로컬 캐시에 저장합니다.',
    '点击收取后会显示 Graph / IMAP / 缓存来源。': '수신 후 Graph / IMAP / 캐시 출처를 표시합니다.',
    '到 Claw 账号页选择子邮箱后再读取邮件。': 'Claw 계정 페이지에서 하위 메일함을 선택한 뒤 읽어주세요.',
    '到账号页选择邮箱后再读取邮件。': '계정 페이지에서 메일을 선택한 뒤 읽어주세요.',
    '立即收取': '지금 수신',
    '邮箱地址已复制': '메일 주소가 복사되었습니다',
    '异常': '오류',
    '复制邮箱': '메일 복사',
    '删除': '삭제',
    '已刷新': '새로고침됨',
    '批量操作': '일괄 작업',
    '批量收件': '일괄 수신',
    '选择账号': '계정 선택',
    '点击左侧账号后，可查看状态、标记颜色并执行收件。': '왼쪽 계정을 선택하면 상태, 표시 색상, 수신 작업을 확인할 수 있습니다.',
    '最近刷新': '최근 새로고침',
    '数据库维护': '데이터베이스 유지관리',
    '处理中': '처리 중',
    '文件': '파일',
    '大小': '크기',
    '重复/孤立': '중복 / 고립',
    '健康检查': '상태 검사',
    '预检查': '사전 검사',
    '修复缓存': '캐시 복구',
    '压缩优化': '압축 최적화',
    '邮件助手': '메일 도우미',
    '待选择': '선택 대기',
    '已识别': '인식됨',
    '未识别': '미인식',
    '验证码': '인증 코드',
    '等待识别': '인식 대기',
    '自动提取当前邮件正文中的 4-8 位数字。': '현재 메일 본문에서 4-8자리 숫자를 자동 추출합니다.',
    '日期': '날짜',
    '正文': '본문',
    '无预览': '미리보기 없음',
    '已缓存': '캐시됨',
    '当前邮件': '현재 메일',
    '选择一封邮件后显示发件人、日期和缓存状态。': '메일을 선택하면 보낸 사람, 날짜, 캐시 상태를 표시합니다.',
    '快捷动作': '빠른 작업',
    '复制验证码': '코드 복사',
    '未识别到数字验证码': '숫자 인증 코드를 찾지 못했습니다',
    '复制正文': '본문 복사',
    '当前邮件没有正文缓存': '현재 메일에 본문 캐시가 없습니다',
    '复制当前邮件纯文本': '현재 메일의 일반 텍스트 복사',
    '已复制到剪贴板': '클립보드에 복사됨',
    '刷新': '새로고침',
    '浏览器授权': '브라우저 인증',
    '批量导入': '일괄 가져오기',
    '账号信息': '계정 정보',
    '标记': '표시',
    '状态': '상태',
    '操作': '작업',
    '同步': '동기화',
    '当前显示 ClawEmail 子邮箱，不混用 Outlook 令牌账号。':
        '현재 ClawEmail 하위 메일함만 표시하며 Outlook 토큰 계정과 섞지 않습니다.',
    '暂无 Claw 子邮箱': 'Claw 하위 메일함 없음',
    '子邮箱': '하위 메일함',
    '类型': '유형',
    '复制子邮箱': '하위 메일함 복사',
    'Claw 子邮箱已复制': 'Claw 하위 메일함이 복사되었습니다',
    '选择子邮箱': '하위 메일함 선택',
    '点击左侧 Claw 子邮箱后查看状态。': '왼쪽 Claw 하위 메일함을 선택하면 상태를 볼 수 있습니다.',
    '来源': '출처',
    '查看邮件': '메일 보기',
    '批量导入账号': '계정 일괄 가져오기',
    '每行格式：邮箱----密码----client_id----refresh_token。如果 client_id 和令牌顺序反了，后端会自动修正。':
        '한 줄 형식: 메일----비밀번호----client_id----refresh_token. client_id와 토큰 순서가 바뀌면 백엔드가 자동 수정합니다.',
    '取消': '취소',
    '导入中': '가져오는 중',
    '导入': '가져오기',
    '浏览器授权登录': '브라우저 인증 로그인',
    '会打开系统浏览器完成 Microsoft 授权，成功后自动写入账号。':
        '시스템 브라우저에서 Microsoft 인증을 완료하고 성공하면 계정에 자동 저장합니다.',
    '适合没有现成 refresh token 的普通 Outlook / Hotmail 账号。':
        '기존 refresh token이 없는 일반 Outlook / Hotmail 계정에 적합합니다.',
    '等待授权': '인증 대기',
    '打开浏览器': '브라우저 열기',
    '正在创建授权会话...': '인증 세션 생성 중...',
    '授权会话返回不完整。': '인증 세션 응답이 불완전합니다.',
    '浏览器已打开，请完成登录授权。': '브라우저가 열렸습니다. 로그인 인증을 완료하세요.',
    '账号': '계정',
    '已授权并导入': '인증 및 가져오기 완료',
    '授权失败': '인증 실패',
    '授权等待超时，请重新打开浏览器授权。': '인증 대기 시간이 초과되었습니다. 브라우저 인증을 다시 열어주세요.',
    '已绑定': '연결됨',
    '未绑定': '연결 안 됨',
    '绑定 Claw 后可同步子邮箱和通讯规则。': 'Claw를 연결하면 하위 메일함과 통신 규칙을 동기화할 수 있습니다.',
    'Claw 登录邮箱': 'Claw 로그인 메일',
    '发送验证码': '인증 코드 보내기',
    '验证码已发送': '인증 코드가 전송되었습니다',
    '绑定并同步': '연결 및 동기화',
    'Claw 已绑定并同步': 'Claw 연결 및 동기화 완료',
    '刷新授权': '인증 새로고침',
    'Claw 授权已刷新': 'Claw 인증이 새로고침되었습니다',
    '子邮箱已创建': '하위 메일함 생성됨',
    '子邮箱已同步': '하위 메일함 동기화됨',
    '新子邮箱后缀': '새 하위 메일함 접미사',
    '创建': '생성',
    '账号标记': '계정 표시',
    '未标记': '표시 없음',
    '标记颜色': '표시 색상',
    '清除标记': '표시 지우기',
    '清除': '지우기',
    '蓝': '파란색',
    '绿': '초록색',
    '橙': '주황색',
    '红': '빨간색',
    '紫': '보라색',
    '青': '청록색',
    '搜索邮箱、名称或 client id': '메일, 이름 또는 client id 검색',
    '健康检查完成': '상태 검사 완료',
    '修复完成，剩余问题': '복구 완료, 남은 문제',
    '已压缩': '압축됨',
    '预检查完成': '사전 검사 완료',
    '可处理：空 ID': '처리 가능: 빈 ID',
    '，重复': ', 중복',
    '，孤立': ', 고립',
  };
}
