part of 'app_localizations.dart';

const appUiEn = {
  'Claw 子邮箱': 'Claw Mailboxes',
  '已导入账号': 'Imported Accounts',
  '已同步列表': 'Synced list',
  '全部令牌已载入': 'All tokens loaded',
  '可用子邮箱': 'Available Mailboxes',
  '可立即收件': 'Ready to Fetch',
  '通讯规则正常': 'Rules healthy',
  '等待同步': 'Waiting to sync',
  '缓存邮件': 'Cached Mail',
  '全部邮件': 'All Mail',
  '收件箱': 'Inbox',
  '垃圾箱': 'Junk',
  '本地可读': 'Readable locally',
  '待处理异常': 'Open Issues',
  '优先修复': 'Fix first',
  '今日收件队列': "Today's Queue",
  '管理账号': 'Manage Accounts',
  '未命名子邮箱': 'Unnamed mailbox',
  'Outlook 令牌账号': 'Outlook token account',
  '可用': 'Available',
  '收件同步': 'Mail Sync',
  '待执行': 'Pending',
  '账号将同步到本地缓存，完成后可在邮件页直接阅读。':
      'Accounts sync into the local cache, then can be read directly in Mail.',
  '最近邮件': 'Recent Mail',
  '暂无邮件': 'No mail yet',
  '暂无 Claw 子邮箱，先到 Claw 设置绑定并同步。':
      'No Claw mailboxes yet. Bind and sync in Claw Settings first.',
  '暂无账号，先导入 Outlook 令牌账号。':
      'No accounts yet. Import Outlook token accounts first.',
  '有异常': 'Issue',
  '缓存': 'Cache',
  '搜索邮件、验证码或发件人': 'Search mail, codes, or senders',
  '先在 Claw 账号页选择子邮箱。': 'Select a Claw mailbox on the Accounts page first.',
  '先在账号页选择邮箱。': 'Select an account on the Accounts page first.',
  '收取': 'Fetch',
  '选择一封邮件开始阅读': 'Select a message to start reading',
  '无正文预览。': 'No body preview.',
  '暂无缓存邮件': 'No cached mail yet',
  '先选择一个 Claw 子邮箱': 'Select a Claw mailbox first',
  '先选择一个账号': 'Select an account first',
  '点击收取后会从 Claw Coremail 拉取并写入本地缓存。':
      'Fetch pulls from Claw Coremail and writes to the local cache.',
  '点击收取后会显示 Graph / IMAP / 缓存来源。':
      'Fetch will show the Graph / IMAP / cache source.',
  '到 Claw 账号页选择子邮箱后再读取邮件。':
      'Choose a Claw mailbox on Accounts before reading mail.',
  '到账号页选择邮箱后再读取邮件。': 'Choose an account before reading mail.',
  '立即收取': 'Fetch Now',
  '邮箱地址已复制': 'Email address copied',
  '异常': 'Error',
  '复制邮箱': 'Copy Email',
  '删除': 'Delete',
  '已刷新': 'Refreshed',
  '批量操作': 'Batch Actions',
  '批量收件': 'Batch Fetch',
  '选择账号': 'Select Account',
  '点击左侧账号后，可查看状态、标记颜色并执行收件。':
      'Select an account on the left to view status, marker color, and fetch mail.',
  '最近刷新': 'Last Refresh',
  '数据库维护': 'Database Maintenance',
  '处理中': 'Working',
  '文件': 'File',
  '大小': 'Size',
  '重复/孤立': 'Duplicate / Orphan',
  '健康检查': 'Health Check',
  '预检查': 'Precheck',
  '修复缓存': 'Repair Cache',
  '压缩优化': 'Compact',
  '邮件助手': 'Mail Helper',
  '待选择': 'Waiting',
  '已识别': 'Detected',
  '未识别': 'Not Detected',
  '验证码': 'Code',
  '等待识别': 'Waiting',
  '自动提取当前邮件正文中的 4-8 位数字。':
      'Automatically extracts 4-8 digit codes from the current mail body.',
  '日期': 'Date',
  '正文': 'Body',
  '无预览': 'No preview',
  '已缓存': 'Cached',
  '当前邮件': 'Current Mail',
  '选择一封邮件后显示发件人、日期和缓存状态。':
      'Select a message to show sender, date, and cache status.',
  '快捷动作': 'Quick Actions',
  '复制验证码': 'Copy Code',
  '未识别到数字验证码': 'No numeric code detected',
  '复制正文': 'Copy Body',
  '当前邮件没有正文缓存': 'No cached body for this message',
  '复制当前邮件纯文本': 'Copy current plain text',
  '已复制到剪贴板': 'Copied to clipboard',
  '刷新': 'Refresh',
  '浏览器授权': 'Browser Login',
  '批量导入': 'Batch Import',
  '账号信息': 'Account',
  '标记': 'Marker',
  '状态': 'Status',
  '操作': 'Actions',
  '同步': 'Sync',
  '当前显示 ClawEmail 子邮箱，不混用 Outlook 令牌账号。':
      'Showing ClawEmail mailboxes only, separate from Outlook token accounts.',
  '暂无 Claw 子邮箱': 'No Claw mailboxes yet',
  '子邮箱': 'Mailbox',
  '类型': 'Type',
  '复制子邮箱': 'Copy Mailbox',
  'Claw 子邮箱已复制': 'Claw mailbox copied',
  '选择子邮箱': 'Select Mailbox',
  '点击左侧 Claw 子邮箱后查看状态。':
      'Select a Claw mailbox on the left to view its status.',
  '来源': 'Source',
  '查看邮件': 'View Mail',
  '批量导入账号': 'Batch Import Accounts',
  '每行格式：邮箱----密码----client_id----refresh_token。如果 client_id 和令牌顺序反了，后端会自动修正。':
      'One line per account: email----password----client_id----refresh_token. If client_id and token are reversed, the backend corrects them.',
  '取消': 'Cancel',
  '导入中': 'Importing',
  '导入': 'Import',
  '浏览器授权登录': 'Browser Authorization Login',
  '会打开系统浏览器完成 Microsoft 授权，成功后自动写入账号。':
      'Opens the system browser for Microsoft authorization and saves the account after success.',
  '适合没有现成 refresh token 的普通 Outlook / Hotmail 账号。':
      'For regular Outlook / Hotmail accounts without an existing refresh token.',
  '等待授权': 'Waiting',
  '打开浏览器': 'Open Browser',
  '正在创建授权会话...': 'Creating authorization session...',
  '授权会话返回不完整。': 'Authorization session response is incomplete.',
  '浏览器已打开，请完成登录授权。': 'Browser opened. Complete the login authorization.',
  '账号': 'Account',
  '已授权并导入': 'authorized and imported',
  '授权失败': 'Authorization failed',
  '授权等待超时，请重新打开浏览器授权。': 'Authorization timed out. Open the browser again.',
  '已绑定': 'Connected',
  '未绑定': 'Not Connected',
  '绑定 Claw 后可同步子邮箱和通讯规则。':
      'Connect Claw to sync mailboxes and communication rules.',
  'Claw 登录邮箱': 'Claw Login Email',
  '发送验证码': 'Send Code',
  '验证码已发送': 'Code sent',
  '绑定并同步': 'Connect and Sync',
  'Claw 已绑定并同步': 'Claw connected and synced',
  '刷新授权': 'Refresh Auth',
  'Claw 授权已刷新': 'Claw auth refreshed',
  '子邮箱已创建': 'Mailbox created',
  '子邮箱已同步': 'Mailboxes synced',
  '新子邮箱后缀': 'New mailbox suffix',
  '创建': 'Create',
  '账号标记': 'Account Marker',
  '未标记': 'Unmarked',
  '标记颜色': 'Marker Color',
  '清除标记': 'Clear Marker',
  '清除': 'Clear',
  '搜索邮件…': 'Search mail…',
  '验证码邮件': 'Verification Codes',
  '收取邮件': 'Fetch Mail',
  '尚未导入账号': 'No accounts imported yet',
  '通用': 'General',
  '服务': 'Server',
  '数据库': 'Database',
  '主题色': 'Accent Color',
  '更改按钮和强调色': 'Change button and accent color',
  '搜索账号…': 'Search accounts…',
  '检查': 'Check',
  '检查中': 'Checking',
  '授权': 'Auth',
  '批量收取': 'Batch Fetch',
  '批量删除': 'Batch Delete',
  '已复制': 'Copied',
  '自动识别 · 请勿分享此验证码': 'Auto-detected. Do not share this code.',
  '黑': 'Black',
  '靛': 'Indigo',
  '刷新当前邮箱缓存': 'Refresh current mailbox cache',
  '在浏览器打开': 'Open in browser',
  '蓝': 'Blue',
  '绿': 'Green',
  '橙': 'Orange',
  '红': 'Red',
  '紫': 'Purple',
  '青': 'Cyan',
  '搜索邮箱、名称或 client id': 'Search email, name, or client id',
  '健康检查完成': 'Health check complete',
  '修复完成，剩余问题': 'Repair complete, remaining issues',
  '已压缩': 'Compacted',
  '预检查完成': 'Precheck complete',
  '可处理：空 ID': 'Can fix: empty ID',
  '，重复': ', duplicate',
  '，孤立': ', orphan',
};
