part of 'app_localizations.dart';

const appStringsJa = AppStrings._(
  appTitle: 'メールワークスペース',
  workspace: 'メールワークスペース',
  dashboard: 'ダッシュボード',
  accounts: 'アカウント',
  mail: 'メール',
  settings: '設定',
  clawSettings: 'Claw 設定',
  outlookChannel: 'Outlook チャネル',
  clawChannel: 'Claw チャネル',
  outlookChannelDetail: 'トークン受信とキャッシュ',
  clawChannelDetail: 'サブメールボックスとルール',
  dashboardSubtitle: '受信、状態、最近の動きをまとめて確認します。',
  accountsSubtitle: 'トークンアカウント、マーク、グループを管理します。',
  mailSubtitle: 'キャッシュ閲覧、認証コード検出、コピーを行います。',
  clawSubtitle: 'ClawEmail の連携とサブメールボックス同期。',
  settingsSubtitle: 'ポート、起動、通知音、言語の設定。',
  fetching: '受信中',
  startFetch: '受信開始',
  clawFetch: 'Claw 受信',
  refreshAccounts: '更新',
  syncing: '同期中',
  fetchLatest: '最新を受信',
  syncClaw: 'Claw 同期',
  testConnection: '接続テスト',
  languageTitle: '表示言語',
  languageDetail: 'デスクトップ UI の主要テキストを切り替えます。',
  autoStartTitle: '自動起動',
  autoStartDetail: 'EXE 起動時にローカル API ポートを作成します。',
  enabled: '有効',
  autoReceiveTitle: '自動受信',
  autoReceiveDetail: '利用可能な Outlook アカウントを定期的に巡回し、新着時に通知します。',
  portPolicyTitle: 'ポート設定',
  portPolicyDetail: '3000 が使用中の場合は次の空きポートを使います。',
  autoSwitch: '自動切替',
  soundTitle: '通知音',
  soundDetail: '新着メール時に通知音を再生します。',
  localApiEngine: 'ローカル API エンジン',
  apiEngineDetail:
      'Flutter はデスクトップ UI を担当し、受信、DB、Claw 連携は Rust sidecar が処理します。',
  autoReceiveInterval: '自動受信間隔',
  selectSound: '通知音を選択',
  preview: '試聴',
  minute: '分',
  bootingApi: 'ローカル API を起動中',
  loadingAccounts: 'アカウントを読み込み中',
  ready: '準備完了',
  needsAttention: '確認が必要',
  refreshingData: 'データを更新中',
  refreshFailed: '更新失敗',
  fetchingMail: 'メールを受信中',
  noNewMail: '新着なし',
  fetchDone: '受信完了',
  fetchFailed: '受信失敗',
  batchFetching: '一括受信中',
  batchFetchDone: '一括受信完了',
  batchFetchFailed: '一括受信失敗',
  fetchingClawMail: 'Claw メールを受信中',
  clawNoNewMail: 'Claw 新着なし',
  clawFetchDone: 'Claw 受信完了',
  clawFetchFailed: 'Claw 受信失敗',
  importingAccounts: 'アカウントをインポート中',
  importDone: 'インポート完了',
  importFailed: 'インポート失敗',
  accountDeleted: 'アカウントを削除しました',
  markerUpdated: 'マークを更新しました',
  localApiNotStarted: 'ローカル API が起動していません。',
  soundMailLabel: 'クリアメール',
  soundMailDescription: '二音階の新着メール通知',
  soundSoftLabel: 'ソフト通知',
  soundSoftDescription: '控えめな柔らかい通知',
  soundNoticeLabel: '注意通知',
  soundNoticeDescription: '確認が必要な時に使用',
  soundSuccessLabel: '完了通知',
  soundSuccessDescription: '同期完了のフィードバック',
  soundUrgentLabel: '強い通知',
  soundUrgentDescription: '認証コードや異常時の通知',
);

const appStringsEn = AppStrings._(
  appTitle: 'Mail Workspace',
  workspace: 'Mail Workspace',
  dashboard: 'Dashboard',
  accounts: 'Accounts',
  mail: 'Mail',
  settings: 'Settings',
  clawSettings: 'Claw Settings',
  outlookChannel: 'Outlook Channel',
  clawChannel: 'Claw Channel',
  outlookChannelDetail: 'Token fetch and cache',
  clawChannelDetail: 'Mailboxes and rules',
  dashboardSubtitle: 'Mail, status, and recent activity in one place.',
  accountsSubtitle: 'Token accounts, markers, and grouping.',
  mailSubtitle: 'Cached reading, code detection, and copy helpers.',
  clawSubtitle: 'ClawEmail binding and mailbox sync.',
  settingsSubtitle: 'Ports, startup, sound, and language preferences.',
  fetching: 'Fetching',
  startFetch: 'Start Fetch',
  clawFetch: 'Claw Fetch',
  refreshAccounts: 'Refresh Accounts',
  syncing: 'Syncing',
  fetchLatest: 'Fetch Latest',
  syncClaw: 'Sync Claw',
  testConnection: 'Test Connection',
  languageTitle: 'Interface Language',
  languageDetail: 'Switch the main desktop interface text.',
  autoStartTitle: 'Auto Start',
  autoStartDetail: 'Create the local API port when the EXE opens.',
  enabled: 'Enabled',
  autoReceiveTitle: 'Auto Receive',
  autoReceiveDetail:
      'Check available Outlook accounts in the background and alert on new mail.',
  portPolicyTitle: 'Port Policy',
  portPolicyDetail: 'Use the next free port when 3000 is occupied.',
  autoSwitch: 'Auto Switch',
  soundTitle: 'Sound Alert',
  soundDetail: 'Play a selectable sound when new mail arrives.',
  localApiEngine: 'Local API Engine',
  apiEngineDetail:
      'Flutter handles the desktop UI; mail, database, and Claw integration are handled by the Rust sidecar.',
  autoReceiveInterval: 'Auto receive interval',
  selectSound: 'Select sound',
  preview: 'Preview',
  minute: 'min',
  bootingApi: 'Starting local API',
  loadingAccounts: 'Loading accounts',
  ready: 'Ready',
  needsAttention: 'Needs attention',
  refreshingData: 'Refreshing data',
  refreshFailed: 'Refresh failed',
  fetchingMail: 'Fetching mail',
  noNewMail: 'No new mail',
  fetchDone: 'Fetch complete',
  fetchFailed: 'Fetch failed',
  batchFetching: 'Batch fetching',
  batchFetchDone: 'Batch fetch complete',
  batchFetchFailed: 'Batch fetch failed',
  fetchingClawMail: 'Fetching Claw mail',
  clawNoNewMail: 'No new Claw mail',
  clawFetchDone: 'Claw fetch complete',
  clawFetchFailed: 'Claw fetch failed',
  importingAccounts: 'Importing accounts',
  importDone: 'Import complete',
  importFailed: 'Import failed',
  accountDeleted: 'Account deleted',
  markerUpdated: 'Marker updated',
  localApiNotStarted: 'Local API is not running.',
  soundMailLabel: 'Crisp Mail',
  soundMailDescription: 'Two-tone new mail alert',
  soundSoftLabel: 'Soft Alert',
  soundSoftDescription: 'Low-interruption gentle alert',
  soundNoticeLabel: 'Notice Alert',
  soundNoticeDescription: 'Use when attention is needed',
  soundSuccessLabel: 'Success Alert',
  soundSuccessDescription: 'Feedback after sync completes',
  soundUrgentLabel: 'Urgent Alert',
  soundUrgentDescription: 'For codes or errors',
);
