part of 'app_localizations.dart';

const appStringsZhHans = AppStrings._(
  appTitle: '邮箱工作台',
  workspace: '邮箱工作台',
  dashboard: '工作台',
  accounts: '账号',
  mail: '邮件',
  settings: '设置',
  clawSettings: 'Claw 设置',
  outlookChannel: 'Outlook 通道',
  clawChannel: 'Claw 通道',
  outlookChannelDetail: '令牌收件与缓存',
  clawChannelDetail: '子邮箱与通讯规则',
  dashboardSubtitle: '收件、状态和最近动态集中处理。',
  accountsSubtitle: '令牌账号、标记和分组管理。',
  mailSubtitle: '缓存阅读、验证码识别和复制。',
  clawSubtitle: 'ClawEmail 绑定与子邮箱同步。',
  settingsSubtitle: '端口、启动、声音和语言偏好。',
  fetching: '收取中',
  startFetch: '开始收取',
  clawFetch: 'Claw 收件',
  refreshAccounts: '刷新账号',
  syncing: '同步中',
  fetchLatest: '收取最新',
  syncClaw: '同步 Claw',
  testConnection: '测试连接',
  languageTitle: '界面语言',
  languageDetail: '切换桌面端主要界面文字。',
  autoStartTitle: '自动启动',
  autoStartDetail: '打开 EXE 后自动创建本地 API 端口。',
  enabled: '已开启',
  autoReceiveTitle: '自动接收',
  autoReceiveDetail: '按间隔后台巡检可用 Outlook 账号，有新邮件时提醒。',
  portPolicyTitle: '端口策略',
  portPolicyDetail: '3000 被占用时改用下一个可用端口。',
  autoSwitch: '自动切换',
  soundTitle: '声音提示',
  soundDetail: '新邮件到达时播放提醒，可选择提示音。',
  localApiEngine: '本地 API 引擎',
  apiEngineDetail: 'Flutter 只负责桌面 UI，收件、数据库和 Claw 适配继续由 Rust sidecar 处理。',
  autoReceiveInterval: '自动接收间隔',
  selectSound: '选择提示音',
  preview: '试听',
  minute: '分钟',
  bootingApi: '正在启动本地 API',
  loadingAccounts: '正在载入账号',
  ready: '就绪',
  needsAttention: '需要处理',
  refreshingData: '正在刷新数据',
  refreshFailed: '刷新失败',
  fetchingMail: '正在收取邮件',
  noNewMail: '无新邮件',
  fetchDone: '收取完成',
  fetchFailed: '收取失败',
  batchFetching: '正在批量收取',
  batchFetchDone: '批量收取完成',
  batchFetchFailed: '批量收取失败',
  fetchingClawMail: '正在收取 Claw 邮件',
  clawNoNewMail: 'Claw 无新邮件',
  clawFetchDone: 'Claw 收取完成',
  clawFetchFailed: 'Claw 收取失败',
  importingAccounts: '正在导入账号',
  importDone: '导入完成',
  importFailed: '导入失败',
  accountDeleted: '账号已删除',
  markerUpdated: '标记已更新',
  localApiNotStarted: '本地 API 未启动。',
  soundMailLabel: '清脆邮件',
  soundMailDescription: '双音阶新邮件提示',
  soundSoftLabel: '轻提示',
  soundSoftDescription: '低打扰柔和提示',
  soundNoticeLabel: '注意提示',
  soundNoticeDescription: '需要处理时使用',
  soundSuccessLabel: '完成提示',
  soundSuccessDescription: '同步完成反馈',
  soundUrgentLabel: '强提醒',
  soundUrgentDescription: '验证码或异常提醒',
);

const appStringsZhHant = AppStrings._(
  appTitle: '郵箱工作台',
  workspace: '郵箱工作台',
  dashboard: '工作台',
  accounts: '帳號',
  mail: '郵件',
  settings: '設定',
  clawSettings: 'Claw 設定',
  outlookChannel: 'Outlook 通道',
  clawChannel: 'Claw 通道',
  outlookChannelDetail: 'Token 收件與快取',
  clawChannelDetail: '子郵箱與通訊規則',
  dashboardSubtitle: '集中處理收件、狀態與最近動態。',
  accountsSubtitle: 'Token 帳號、標記與分組管理。',
  mailSubtitle: '快取閱讀、驗證碼辨識與複製。',
  clawSubtitle: 'ClawEmail 綁定與子郵箱同步。',
  settingsSubtitle: '連接埠、啟動、聲音與語言偏好。',
  fetching: '收取中',
  startFetch: '開始收取',
  clawFetch: 'Claw 收件',
  refreshAccounts: '重新整理帳號',
  syncing: '同步中',
  fetchLatest: '收取最新',
  syncClaw: '同步 Claw',
  testConnection: '測試連線',
  languageTitle: '介面語言',
  languageDetail: '切換桌面端主要介面文字。',
  autoStartTitle: '自動啟動',
  autoStartDetail: '開啟 EXE 後自動建立本地 API 連接埠。',
  enabled: '已開啟',
  autoReceiveTitle: '自動接收',
  autoReceiveDetail: '依間隔背景巡檢可用 Outlook 帳號，有新郵件時提醒。',
  portPolicyTitle: '連接埠策略',
  portPolicyDetail: '3000 被占用時改用下一個可用連接埠。',
  autoSwitch: '自動切換',
  soundTitle: '聲音提示',
  soundDetail: '新郵件到達時播放提醒，可選擇提示音。',
  localApiEngine: '本地 API 引擎',
  apiEngineDetail: 'Flutter 只負責桌面 UI，收件、資料庫與 Claw 適配繼續由 Rust sidecar 處理。',
  autoReceiveInterval: '自動接收間隔',
  selectSound: '選擇提示音',
  preview: '試聽',
  minute: '分鐘',
  bootingApi: '正在啟動本地 API',
  loadingAccounts: '正在載入帳號',
  ready: '就緒',
  needsAttention: '需要處理',
  refreshingData: '正在重新整理資料',
  refreshFailed: '重新整理失敗',
  fetchingMail: '正在收取郵件',
  noNewMail: '沒有新郵件',
  fetchDone: '收取完成',
  fetchFailed: '收取失敗',
  batchFetching: '正在批次收取',
  batchFetchDone: '批次收取完成',
  batchFetchFailed: '批次收取失敗',
  fetchingClawMail: '正在收取 Claw 郵件',
  clawNoNewMail: 'Claw 沒有新郵件',
  clawFetchDone: 'Claw 收取完成',
  clawFetchFailed: 'Claw 收取失敗',
  importingAccounts: '正在匯入帳號',
  importDone: '匯入完成',
  importFailed: '匯入失敗',
  accountDeleted: '帳號已刪除',
  markerUpdated: '標記已更新',
  localApiNotStarted: '本地 API 尚未啟動。',
  soundMailLabel: '清脆郵件',
  soundMailDescription: '雙音階新郵件提示',
  soundSoftLabel: '輕提示',
  soundSoftDescription: '低干擾柔和提示',
  soundNoticeLabel: '注意提示',
  soundNoticeDescription: '需要處理時使用',
  soundSuccessLabel: '完成提示',
  soundSuccessDescription: '同步完成回饋',
  soundUrgentLabel: '強提醒',
  soundUrgentDescription: '驗證碼或異常提醒',
);
