part of 'app_localizations.dart';

const appStringsKo = AppStrings._(
  appTitle: '메일 작업대',
  workspace: '메일 작업대',
  dashboard: '대시보드',
  accounts: '계정',
  mail: '메일',
  settings: '설정',
  clawSettings: 'Claw 설정',
  outlookChannel: 'Outlook 채널',
  clawChannel: 'Claw 채널',
  outlookChannelDetail: '토큰 수신 및 캐시',
  clawChannelDetail: '하위 메일함과 규칙',
  dashboardSubtitle: '수신, 상태, 최근 활동을 한곳에서 확인합니다.',
  accountsSubtitle: '토큰 계정, 표시, 그룹을 관리합니다.',
  mailSubtitle: '캐시 읽기, 인증 코드 감지, 복사 도구.',
  clawSubtitle: 'ClawEmail 연결 및 하위 메일함 동기화.',
  settingsSubtitle: '포트, 시작, 소리, 언어 설정.',
  fetching: '수신 중',
  startFetch: '수신 시작',
  clawFetch: 'Claw 수신',
  refreshAccounts: '계정 새로고침',
  syncing: '동기화 중',
  fetchLatest: '최신 수신',
  syncClaw: 'Claw 동기화',
  testConnection: '연결 테스트',
  languageTitle: '인터페이스 언어',
  languageDetail: '데스크톱 주요 UI 문구를 전환합니다.',
  autoStartTitle: '자동 시작',
  autoStartDetail: 'EXE 실행 시 로컬 API 포트를 만듭니다.',
  enabled: '켜짐',
  autoReceiveTitle: '자동 수신',
  autoReceiveDetail: '사용 가능한 Outlook 계정을 백그라운드로 확인하고 새 메일을 알립니다.',
  portPolicyTitle: '포트 정책',
  portPolicyDetail: '3000이 사용 중이면 다음 사용 가능 포트를 씁니다.',
  autoSwitch: '자동 전환',
  soundTitle: '소리 알림',
  soundDetail: '새 메일 도착 시 선택한 알림음을 재생합니다.',
  localApiEngine: '로컬 API 엔진',
  apiEngineDetail:
      'Flutter는 데스크톱 UI를 맡고, 수신, DB, Claw 연동은 Rust sidecar가 처리합니다.',
  autoReceiveInterval: '자동 수신 간격',
  selectSound: '알림음 선택',
  preview: '미리 듣기',
  minute: '분',
  bootingApi: '로컬 API 시작 중',
  loadingAccounts: '계정 불러오는 중',
  ready: '준비됨',
  needsAttention: '확인 필요',
  refreshingData: '데이터 새로고침 중',
  refreshFailed: '새로고침 실패',
  fetchingMail: '메일 수신 중',
  noNewMail: '새 메일 없음',
  fetchDone: '수신 완료',
  fetchFailed: '수신 실패',
  batchFetching: '일괄 수신 중',
  batchFetchDone: '일괄 수신 완료',
  batchFetchFailed: '일괄 수신 실패',
  fetchingClawMail: 'Claw 메일 수신 중',
  clawNoNewMail: 'Claw 새 메일 없음',
  clawFetchDone: 'Claw 수신 완료',
  clawFetchFailed: 'Claw 수신 실패',
  importingAccounts: '계정 가져오는 중',
  importDone: '가져오기 완료',
  importFailed: '가져오기 실패',
  accountDeleted: '계정 삭제됨',
  markerUpdated: '표시가 업데이트됨',
  localApiNotStarted: '로컬 API가 시작되지 않았습니다.',
  soundMailLabel: '맑은 메일음',
  soundMailDescription: '두 음의 새 메일 알림',
  soundSoftLabel: '부드러운 알림',
  soundSoftDescription: '방해가 적은 부드러운 알림',
  soundNoticeLabel: '주의 알림',
  soundNoticeDescription: '확인이 필요할 때 사용',
  soundSuccessLabel: '완료 알림',
  soundSuccessDescription: '동기화 완료 피드백',
  soundUrgentLabel: '강한 알림',
  soundUrgentDescription: '인증 코드 또는 오류 알림',
);
